### ISSUE TITLE
Unklarheit bei Judas'  Tipps für den Spielleiter

### ISSUE THREAD

**Issue by hnrch02** [gamekeller/mafia#11]
Was genau soll

> - Judas zählt nicht in der Rechnung: Spieler = Mafia win.

heißen? Das bedarf näherer Ausführung.

**Comment by hnrch02** [comment]
Ähnliches gilt auch für die Tipps bei dem Geist:

> - Der Geist zählt auch nicht in der Rechnung: Mafia Gewinnbedingungen.

**Comment by MigoBurgghardti** [comment]
Wenn die Anzahl der Mafia gleich so viel wie die Anzahl der Town ist hat die Town verloren. Die Regel habe ich aber raus genommen weil es soviele ausnahmen gab. Siehe: Thirdparty, Busfahrer, Veteran, Samurai, Barbar, Ausrüster und viele mehr. Es ist schwer eigentlich ergibt es sind die Mafia = Town verliert Siegbedingung rein zu machen, aber es gibt einfach zu viele Ausnahmen. :( Zwiespalt ^^
