### ISSUE TITLE
[Roles] Bürgermeister

### ISSUE THREAD

**Issue by JuriSchreib** [gamekeller/mafia#16]
Der Bürgermeister (alt. Präsident, Premiereminister) wird am Anfang von dem Mitspielern gewählt. Er behält seine Ursprüngliche Rolle und seine Spielweiße ändert sich nicht. Jedoch ist der Lynchphase ein Vote von ihm 2 Punkte wert. Bei Gleichstand in der Lnychphase gilt nicht die 50% Regel, sondern es zählt das wofür auch der Bürgermeister gestimmt hat. Falls der Bürgermeister sterben sollte, wird ein neuer gewählt

Quelle: Die Werwölfe von Düsterwald

**Comment by MigoBurgghardti** [comment]
:+1:

**Comment by MigoBurgghardti** [comment]
:ok_hand:

**Comment by hnrch02** [comment]
:ship: it.

**Comment by hnrch02** [comment]
@Bujuhu Kann man eine PR erwarten, oder wie sieht's aus?

**Comment by MigoBurgghardti** [comment]
Heißt im Englishen btw. Doublevoter und gibt es auch im Mafia Universum.
