### ISSUE TITLE
Cop Variante: Kaufhauscop

### ISSUE THREAD

**Issue by ghost** [gamekeller/mafia#64]
Andere Variante des Cop's:

Der Kaufhauscop ist so wie der normale,heißt er kann Leute in der Nacht prüfen. Er hat aber ein Schuss (wie Veteran), bloß wenn er damit einen Town tötet verliert er (entweder:) sein Leben oder seine Fähigkeit in der Nacht Leute zu prüfen (wird zu Bürger).

**Comment by ThePaddy** [comment]
Also wie der Samurai?

**Comment by ghost** [comment]
Naja wenn man so spielt das er seine Fähigkeit verliert dann nicht ;)
Außerdem ist er immer noch ein Cop und er muss nicht "morden".

**Comment by MigoBurgghardti** [comment]
Entweder? Kann er sich das aussuchen?

**Comment by ghost** [comment]
Hätte es jetzt gemeint, dass dies der Spielleiter aussucht oder ihr mir sagt was besser für's Spielgesschehen wäre ... wollte die Rolle nicht zu unfair aber auch nicht zu schlecht gestalten.
