### ISSUE TITLE
Landingpage

### ISSUE THREAD

**Issue by MigoBurgghardti** [gamekeller/mafia#7]
Auf der könnten wir Social Media, die Gamekeller Main Page und das Teamspeak verlinken.
Außerdem könnten wir eine kurze Erklärung zu Mafia geben.
Neu angeworbene Spieler müssten nicht viel erklärt bekommen da er Komplett durch die Seite erklärt werden würde.

**Comment by hnrch02** [comment]
Find ich ne gute Idee, setzt ich mich mal in näherer Zukunft dran.

**Comment by MigoBurgghardti** [comment]
"Yeti just requested a definition of "näherer Zukunft"."

**Comment by hnrch02** [comment]
Wie hoch ist die Priorität? Ich hab's mir jetzt mal aufgeschrieben, würd' mich wahrscheinlich in den nächsten paar Wochen ransetzen.

**Comment by MigoBurgghardti** [comment]
Prima, mir wäre vielleicht wichtig das man dort auch die "Patchnotes" rein bastelt wie zb. : Rolle bla ist neu, Rolle xy wurde verändert.

**Comment by hnrch02** [comment]
Changelog klingt super.

Am 26. Juni 2014 12:08 schrieb Yeti Cory notifications@github.com:

**Comment by MigoBurgghardti** [comment]
"Ich hab's mir jetzt mal aufgeschrieben, würd' mich wahrscheinlich in den nächsten paar Wochen ransetzen." @hnrch02 "Jun 25, 2014"

_cough cough_

**Comment by hnrch02** [comment]
Haha, ja, das ist ein bisschen im Sand verlaufen. Vielleicht willst du es ja machen?
