### ISSUE TITLE
Ist es nötig zu erklären wie das Voting System funktioniert?

### ISSUE THREAD

**Issue by MigoBurgghardti** [gamekeller/mafia#8]
Ich erkläre es eigentlich jede Runde nochmal allerdings wird das nicht jeder Spielleiter machen.

**Comment by hnrch02** [comment]
Könnte man in dem GM-Guide erwähnen, ja.

**Comment by MigoBurgghardti** [comment]
Stimmt, spart man an Pages. Sieht sonst eh zu überladen aus ;)
